### ISSUE TITLE
attempt to call field 'create_osd_overlay' (a nil value)

### ISSUE THREAD

**Issue by edulim** [Ajatt-Tools/mpvacious#1]
Platform: Debian 10 Buster
mpv version: 0.29.1

Hello, I followed the installation instructions, but I'm getting this error when I play a video with mpv. I can still watch the video, but the script doesn't work.

```
[modules]
[modules] stack traceback:
[modules]       /home/user/.config/mpv/scripts/subs2srs/subs2srs.lua:737: in main chunk
[modules]       [C]: in function 'dofile'
[modules]       /home/user/.config/mpv/scripts/modules.lua:2: in function 'load'
[modules]       /home/user/.config/mpv/scripts/modules.lua:3: in main chunk
[modules]       [C]: in ?
[modules]       [C]: in ?
[modules] Lua error: /home/user/.config/mpv/scripts/subs2srs/subs2srs.lua:737: attempt to call field 'create_osd_overlay' (a nil value)
```

**Comment by rentatsumoto** [comment]
mp.create_osd_overlay() is a function that didn't exist in mpv 0.29.1. It was added in v0.32.0.

**Comment by rentatsumoto** [comment]
I pushed a fix that should avoid the crash, but users of older versions of mpv won't be able to access the OSD menu. It leaves them with only a few global key bindings. To actually fix the issue you need to upgrade mpv itself.

**Comment by edulim** [comment]
Ok, I have update my mpv to 0.32.0. Thank you.

**Comment by edulim** [comment]
Ok, I have updated my mpv to 0.32.0. Thank you.

**Comment by edulim** [comment]
Ok. I have updated my mpv to 0.32.0. Thank you.

**Comment by edulim** [comment]
Ok. I have updated my mpv to 0.32.0. Thank you.

**Comment by edulim** [comment]
Ok. I have updated my mpv to 0.32.0. Thank you.

**Comment by edulim** [comment]
Ok. I have updated my mpv to 0.32.0. Thank you.

**Comment by edulim** [comment]
Ok. I have updated my mpv to 0.32.0. Thank you.

**Comment by edulim** [comment]
Ok. I have updated my mpv to 0.32.0. Thank you.
