### ISSUE TITLE
Image appears in very low quality in flashcard

### ISSUE THREAD

**Issue by kaladin-syl** [Ajatt-Tools/mpvacious#10]
**Environment:**

- OS: Manjaro KDE
- OS: 20.2
- mpv version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100 (runtime 56.51.100)
   libavcodec      58.54.100 (runtime 58.91.100)
   libavformat     58.29.100 (runtime 58.45.100)
   libswscale      5.5.100 (runtime 5.7.100)
   libavfilter     7.57.100 (runtime 7.85.100)
   libswresample   3.5.100 (runtime 3.7.100)
ffmpeg version: n4.3.1

Title says it all. The original video file is in 1080p. 

[Here's how it looks](https://i.imgur.com/ro0XBJd.png)

**Comment by tatsumoto-ren** [comment]
This feature is intended to reduce file sizes and save space on AnkiWeb. Image quality can be controlled via an option in `~/.config/mpv/script-opts/subs2srs.conf`. Simply specify the desired quality, for example:
```
snapshot_format=webp
snapshot_quality=50
```

**Comment by kaladin-syl** [comment]
Ah, thank you very much :)
