### ISSUE TITLE
Can't make cards while using Celluloid

### ISSUE THREAD

**Issue by EddoWagt** [Ajatt-Tools/mpvacious#100]
**The issue**
I can't get mpvacious with celluloid to create new Anki cards.
The plugin works as I can get the popup when pressing A and automatically copying to clipboard also works.
But pressing Ctrl+n or G doesn't do anything.

Using mpvacious through regular mpv does work (Installed through the fedora repo's just like celluloid), but I highly prefer to use celluloid instead.
I copied my mpvacious mpv connect to celluloid so it should work, but my guess is that something is somehow going wrong with AnkiConnect, I'm just not so sure where and how.

Also not sure how to get logs, I'll supply them if I find out how.

**Environment**

1) Fedora
2) Version 38
3) mpv version 0.25 (Celluloid, Fedora RPM)

**Expected behavior**
The same as in regular mpv

**Comment by tatsumoto-ren** [comment]
Usually problems occur when people use flatpak or snap, but since you say you have installed celluloid from the official repos, I currently have no idea. When you try to create a card, are there any messages on the screen?

**Comment by EddoWagt** [comment]
Nope, nothing appears on screen. Anki is installed through flatpak, but seeing that regular mpv works fine that shouldn't be an issue. There's also no anki package from the repo so I don't have another option really

**Comment by tatsumoto-ren** [comment]
>Nope, nothing appears on screen.

What about the logs? Does mpvacious crash?

**Comment by EddoWagt** [comment]
I don't think so, the rest of the plugin keeps working. Where can I find logs?

**Comment by tatsumoto-ren** [comment]
>Where can I find logs?

If you run celluloid from the terminal, it should print the logs to stdout. Or you can try pressing the tilde key while inside the window to bring up the console.

**Comment by EddoWagt** [comment]
I only get  `Cannot load libcuda.so.1` when opening celluloid
and
`(io.github.celluloid_player.Celluloid:7934): Gtk-CRITICAL **: 22:42:56.025: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed`

A bunch of times, but I don't think either are related to the plugin.
When pressing ctrl+n for example nothing happens or shows up

Also, the tilde key does not show a console for me

**Comment by tatsumoto-ren** [comment]
> Nevermind, it worked with another keyboard.

So, when you press `ctrl+n`, there's still nothing in the console?

**Comment by EddoWagt** [comment]
> So, when you press ctrl+n, there's still nothing in the console?

There is, it's this:
```
[modules] Read config file: subs2srs
[modules] bad argument #1 to '?' (string expected, got nil)
```

**Comment by tatsumoto-ren** [comment]
Strange that it doesn't tell yo in what file and on what line the error occurred. Without such information it's difficult to tell what happened.

**Comment by EddoWagt** [comment]
Indeed, especially since mpv is working perfectly and is reporting stuff in the logs like 
`executing file ...`
Do you have anything else I can try?

**Comment by tatsumoto-ren** [comment]
>Can it have something to do with the 'modules.lua' I had to create?

That's a legacy way of installing user-scripts. Doesn't celluloid support the newer way where you just place the `subs2srs` folder inside `scripts` folder?

**Comment by EddoWagt** [comment]
I don't think so, doing that doesn't do anything

**Comment by nairyosangha** [comment]
> Indeed, especially since mpv is working perfectly and is reporting stuff in the logs like `executing file ...`
> 
> Can it have something to do with the 'modules.lua' I had to create?
> 
> It contains this:
> 
> ```
> local mpv_scripts_dir_path = os.getenv("HOME") ..  "/.config/mpv/scripts/"
> package.path = package.path .. ';' .. os.getenv("HOME") .. '/.config/mpv/scripts/subs2srs/?.lua'
> function load(relative_path) dofile(mpv_scripts_dir_path .. relative_path) end
> load("subs2srs/subs2srs.lua")
> ```
> 
> Edit: I just noticed that when I have no subtitles on display it does tell me "Nothing to export", so I assume that it goes wrong when trying to connect to Anki

I don't think you need to do this, according to the celluloid github page scripts should be supported as is (https://github.com/celluloid-player/celluloid#user-scripts)

It looks like scripts need to go in `~/.config/celluloid/scripts`, in which case they should be picked up.
However, for some reason when I try that it only picks up scripts which are a single file, not scripts which reside in a directory. This is definitely supported by MPV, I don't know why it doesn't work in Celluloid

I can get around it if I do `celluloid --mpv-scripts=~/.config/mpv/scripts/subs2srs`

**Comment by EddoWagt** [comment]
> > Indeed, especially since mpv is working perfectly and is reporting stuff in the logs like `executing file ...`
> > Can it have something to do with the 'modules.lua' I had to create?
> > It contains this:
> > ```
> > local mpv_scripts_dir_path = os.getenv("HOME") ..  "/.config/mpv/scripts/"
> > package.path = package.path .. ';' .. os.getenv("HOME") .. '/.config/mpv/scripts/subs2srs/?.lua'
> > function load(relative_path) dofile(mpv_scripts_dir_path .. relative_path) end
> > load("subs2srs/subs2srs.lua")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Edit: I just noticed that when I have no subtitles on display it does tell me "Nothing to export", so I assume that it goes wrong when trying to connect to Anki
> 
> I don't think you need to do this, according to the celluloid github page scripts should be supported as is (https://github.com/celluloid-player/celluloid#user-scripts)
> 
> It looks like scripts need to go in `~/.config/celluloid/scripts`, in which case they should be picked up. However, for some reason when I try that it only picks up scripts which are a single file, not scripts which reside in a directory. This is definitely supported by MPV, I don't know why it doesn't work in Celluloid
> 
> I can get around it if I do `celluloid --mpv-scripts=~/.config/mpv/scripts/subs2srs`

You're right, with that argument it does work! I guess I need to figure out how to run celluloid with that argument by default

**Comment by tatsumoto-ren** [comment]
That's definitely a hack, and apparently Celluloid just doesn't support scripts inside folders.

> I need to figure out how to run celluloid with that argument by default

Create or edit an exiting a .desktop file.

**Comment by EddoWagt** [comment]
> That's definitely a hack, and apparently Celluloid just doesn't support scripts inside folders.

Yeah it's definitely a hack, but I guess it works. 
Should this topic be marked as closed, since the issue isn't caused by mpvacious?
