### ISSUE TITLE
[sound] audio tag doesn't get rendered in firefox if used with opus filetype 

### ISSUE THREAD

**Issue by kuator** [Ajatt-Tools/mpvacious#103]
Desktop Anki client on the left and Firefox on the right.
![Screenshot from 2023-08-14 18-07-36](https://github.com/Ajatt-Tools/mpvacious/assets/25168308/f5aca62c-ff82-4675-93f5-bfa65698c341)
I have found that `[source]` tag works with opus, so I think it would be viable to implement custom audio_template:

**Comment by kuator** [comment]
https://github.com/Ajatt-Tools/mpvacious/pull/102

**Comment by tatsumoto-ren** [comment]
Ok, thank you!
