### ISSUE TITLE
I'm trying to setup mpvacious with vocabsieve to learn English!

### ISSUE THREAD

**Issue by vNovvy** [Ajatt-Tools/mpvacious#109]
![Screenshot 2023-09-16 074336](https://github.com/Ajatt-Tools/mpvacious/assets/125720543/ca30ff65-b73c-4c42-8a2c-ec7713d3cce1) 

i've tride everything to make the audio goes with the card the i've created but it is not working. 
i've changed a lot of settings on the subs2srs.conf file but still nothing fixed the issue. 
https://www.youtube.com/watch?v=EHW-kBLmuHU&pp=ygUWc2ltcGxlIHNlbnRlbmNlIG1pbmluZw%3D%3D
i watched this video and it's working very well with him.

**Comment by tatsumoto-ren** [comment]
>  the audio goes with the card the i've created but it is not working.

mpvacious doesn't create audio files for you, right? If so, you probably need to check if you have fffmpeg installed and added to the PATH (if you have `use_ffmpeg=yes` set in the config file).

**Comment by vNovvy** [comment]
it worked perfectly,  thank you for your help. <3
