### ISSUE TITLE
Hide subtitles but copy to clipboard

### ISSUE THREAD

**Issue by kanjieater** [Ajatt-Tools/mpvacious#116]
- The add-on crashes?
- The add-on stopped working?
- Have a feature request?

Please ask on https://tatsumoto.neocities.org/blog/join-our-community.html instead. It is easier for our members to provide support over in the chats. Thank you!

Don't forget to provide the following information: 

**Environment**

1) OS name  [e.g. Parabola, Debian]
Windows
2) OS version
11
3) mpv version
mpv 0.35.0-221-ga40958cd Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Feb 12 12:30:03 2023
libplacebo version: v5.229.1-157-g8552809
FFmpeg version: N-109844-g2b4273072
FFmpeg library versions:
   libavutil       58.0.100
   libavcodec      60.1.100
   libavformat     60.2.100
   libswscale      7.0.100
   libavfilter     9.0.100
   libswresample   4.9.100

4) Logs
5) Screenshots, if applicable

**Describe the bug**
Sorry, probably not a bug, but I thought there was a way to hide the subtitles but still have them copy to the clipboard. This way you could watch without subtitles, but if you needed to look up a word while you focusing on listening w/o subs, you could still do so using a text-hooker page without having to press any additional hotkeys or go back.

**To Reproduce**
1) Set MPVacious to copy subs automatically
2) Press j (default key to turn off subtitles)
3) subs stop copying

**Expected behavior**
Subs should always copy when autoclip is set to yes, even if the subs aren't displayed.

**Comment by tatsumoto-ren** [comment]
the `v` hotkey is used to hide the subtitles. if you press `j,` you cycle to the next subtitle track (or disable subtitles completely).
