### ISSUE TITLE
Corrupted Audio (windows 10)

### ISSUE THREAD

**Issue by Lucridius** [Ajatt-Tools/mpvacious#12]
**Describe the bug**
All the audio exported to anki does not play for me (and also won't open up in foobar)
I've tried both opus and mp3

I should note I don't have "curl" installed, but from reading the github page of mpvacious, it just seems like an installer?
(if I'm wrong, and I need curl to get the working audio export please let me know)

![image](https://user-images.githubusercontent.com/38091364/99187604-b71db380-27ab-11eb-90fa-9fc277151242.png)
![image](https://user-images.githubusercontent.com/38091364/99187633-ea604280-27ab-11eb-8f02-c6d324ae8bd3.png)

(as a closing note, great work man)

**Comment by tatsumoto-ren** [comment]
Thank you for your report. Windows 10 includes curl by default so you don't need to install it. As for corrupted audio, I can't reproduce so could you provide the steps? Also make sure your config file exists and is configured according to your setup.

**Comment by Lucridius** [comment]
All I'm doing is.
Opening a video skipping to a line with subtitles.
pressing A>C>N

and then looking at the exported card.

I wasn't using a config file originally (I just made one) but that hasn't solved the issue.
Although I put all my settings in the config I'll post a screenshot of the .lua since I can show you the settings that way.

![image](https://user-images.githubusercontent.com/38091364/99201471-2f619480-27ff-11eb-91ba-1b360e23f57c.png)


So most of my videos use flac audio (I've only test about 3 files) I tried exporting one of the flacs then converting it into a mp3 to see if it wasn't like the flac format, but that didn't work either

**Comment by tatsumoto-ren** [comment]
Config seems fine. Audio padding is too big though. Are you perhaps using a non-standard build of mpv? [This](https://sourceforge.net/projects/mpv-player-windows/files/) one is recommended.

**Comment by Lucridius** [comment]
Oh my gosh, that worked (changing versions)

(also my padding is high because I plan to clean up the audio in post and normalize the volume)

**Comment by tatsumoto-ren** [comment]
It subtracts one second from the beginning of the clip and adds one seconds to the end. So you get two seconds of padding overall.
