### ISSUE TITLE
Copy to clipboard feature is not working for me

### ISSUE THREAD

**Issue by diverenforce** [Ajatt-Tools/mpvacious#121]
- The add-on crashes?no
- The add-on stopped working?no
- Have a feature request?no

Please ask on https://tatsumoto.neocities.org/blog/join-our-community.html instead. It is easier for our members to provide support over in the chats. Thank you!

Don't forget to provide the following information: 

**Environment**

1) OS name  [e.g. Parabola, Debian] Linux Mint 21.3 Cinnamon
2) OS version 21.3
3) mpv version 0.34.1-1ubuntu3 from software manager 
4) Logs
![image](https://github.com/Ajatt-Tools/mpvacious/assets/120410051/27f0912a-3fda-4c39-80df-4d47e02b275b)

5) Screenshots, if applicable

**Describe the bug**
A description of what the bug is.
I installed mpvacious just fine. Opened up an episode for test. Insert its subs. press A + T + A and wait for the subs.
The subs dont show up in clipboard. Spam control v. does not work

**To Reproduce**
1) Press x '...'
2) Click on '....'
3) See error

**Expected behavior**
A description of what you expected to happen.
clipboard is not receiving the subs when its supposed to.

**Comment by tatsumoto-ren** [comment]
Please ask on https://tatsumoto.neocities.org/blog/join-our-community.html instead. It is easier for our members to provide support over in the chats. Thank you!

**Comment by emanuelps2708** [comment]
The issue with the clipboard is also happening to me with the latest release even though I have already installed xclip, the previous one (0.27) works well. 

![image](https://github.com/Ajatt-Tools/mpvacious/assets/147004033/ce92f683-ad01-4733-aa25-b0d78234cc03)


New version:
![image](https://github.com/Ajatt-Tools/mpvacious/assets/147004033/3abd25c7-ed0e-49ad-b764-591b3e01cc93)

Previous one:
![image](https://github.com/Ajatt-Tools/mpvacious/assets/147004033/9168ad5b-6f20-44b4-a9a7-5aa2146dc698)

**Comment by emanuelps2708** [comment]
I will ask on element about this

**Comment by diverenforce** [comment]
also thank you to everyone here installing xclip worked!
