### ISSUE TITLE
mouse wheel changes volume instead of seek

### ISSUE THREAD

**Issue by darkralts** [Ajatt-Tools/mpvacious#126]
how do i fix it

**Comment by tatsumoto-ren** [comment]
>mouse wheel changes volume instead of seek

This appears like a general mpv question rather than something related to mpvacious. But if you want to seek with the mouse wheel, try changing `input.conf` 

```
WHEEL_UP add volume 2
WHEEL_DOWN add volume -2
```

**Comment by darkralts** [comment]
ya i thought it was the script at first so i posted here but its not

**Comment by darkralts** [comment]
thanks

**Comment by tatsumoto-ren** [comment]
You're welcome.
