### ISSUE TITLE
Issues with "Modifying cards added with Yomichan"

### ISSUE THREAD

**Issue by thovip119** [Ajatt-Tools/mpvacious#15]
**Environment:**

OS: Windows 10 Home
Version 2004
mpv 0.32.0-759-g67b4a96e45 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Oct 11 16:36:53 +08 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.111.100
   libavformat     58.62.100
   libswscale      5.8.100
   libavfilter     7.87.100
   libswresample   3.8.100
FFmpeg version: git-2020-10-10-0c73c2909

**Describe the bug** 
When update a note which were added using Yomichan with "m/ Shift +m" key, return "Note # updated" but no change occur aside from media being added to collection.media.

**To Reproduce** Steps to reproduce the behavior:

Add a note using Yomichan with clipboard inserter enabled
Switch to MPV
Click "a", click "m" or "Shift+m"
"Note # updated" is shown but no change was made

**Expected behavior** Screenshot and Audio from the video to be appended to the yomichan card.

**Screenshots** 
subs2srs.conf: https://anotepad.com/notes/9d7cg39t
![2](https://user-images.githubusercontent.com/44400027/102423015-9f4f7e80-403a-11eb-96a0-b462b62a9949.png)
![3](https://user-images.githubusercontent.com/44400027/102423033-a8d8e680-403a-11eb-9a33-1fd27619c5b1.PNG)
![0](https://user-images.githubusercontent.com/44400027/102423034-a9717d00-403a-11eb-906b-aec4dbd11c67.PNG)
![1](https://user-images.githubusercontent.com/44400027/102423035-aa0a1380-403a-11eb-9438-c63389f261aa.png)

**Comment by tatsumoto-ren** [comment]
Hi! Yes, this issue exists. Only **windows** users are affected so I recommend switching to GNU/Linux for now to avoid it. I'll push a quick fix shortly.
