### ISSUE TITLE
[subs2srs] Lua error: [string "~/.config/mpv/scripts/subs2srs...."]:525: attempt to call field 'unpack' (a nil value)   

### ISSUE THREAD

**Issue by aniketpanjwani** [Ajatt-Tools/mpvacious#16]
**Environment:**
 - OS: OSX
 - OS version: 10.15.2
 - mpv version: 0.33.0

**Describe the bug**
When I try to use Ctrl-H on cb39907, I get an error as described in the title and can no longer use any mpvacious shortcuts. I regressed to 3209db20 and it works fine.

**To Reproduce**
1. Place the cb39907 configuration in /.config/mpv/scripts
2. Open a video file with mpv.
3. Enter a, and use advanced controls just fine.
4. Enter Ctrl-H, and get error.

**Comment by tatsumoto-ren** [comment]
If it says
> attempt to call field 'unpack'
then it has to do with the use of `table.unpack` in the functions responsible for seeking. I expect that it's due to an older version of lua used in your build of mpv.

**Comment by tatsumoto-ren** [comment]
Please tell me if this fix solves your issue.

**Comment by aniketpanjwani** [comment]
Thanks, this does solve the issue, but I'm having a different problem, for which I'll create new issue.
