### ISSUE TITLE
seeking to next subtitle not working when there is subtitle playing

### ISSUE THREAD

**Issue by stegatxins0** [Ajatt-Tools/mpvacious#18]
**Environment:**
 - OS: Windows 10
 - OS version: 20H2
 - mpv version: v2020.1.27 

**Describe the bug**
When there is subtitle playing, mpvacious do not seek to next subtitle, instead stay on the current frame. However, seeking to next subtitle functions properly when there is no subtitle on the current frame. 

**To Reproduce**
1. Go to a frame with subtitle playing
2. Press 'Shift + l'
3. See error

**Expected behavior**
mpvacious seek to next subtitle instead of staying on current frame

**Comment by tatsumoto-ren** [comment]
Hi! I tried to reproduce this but couldn't. Though seeking in mpvacious is a bit different from the default mpv bindings, the underlying functions being called are the same. Please check if you can seek normally with default mpv bindings (Ctrl + Left/Right arrow).

**Comment by stegatxins0** [comment]
sorry if i didn't explain it properly but it's something like this: https://youtu.be/gXvXiujD4Uo

**Comment by tatsumoto-ren** [comment]
It likely happens when the scene where the next subtitle line is going to appear is not cached yet. If you increase cache size in `mpv.conf` the problem should disappear.
