### ISSUE TITLE
Choose which frame to use as screenshot

### ISSUE THREAD

**Issue by Lucridius** [Ajatt-Tools/mpvacious#19]
I thought I saw this feature added?
How do you use it? (if it was added)

(sorry if this isn't really an "issue")

thanks

**Comment by tatsumoto-ren** [comment]
Whatever frame is currently displayed on screen is chosen as for the shapshot. 

>How do you use it?

Seek to the right frame before creating a new card.

**Comment by tatsumoto-ren** [comment]
If you have more questions, please ask them in the chat.

**Comment by Lucridius** [comment]
(sorry I somehow missed the "discussions" tab (if that's what you're referring to))

but thank you

**Comment by tatsumoto-ren** [comment]
Not really, I was referring to the matrix group. It is linked in the README.

https://app.element.io/#/room/#djt:g33k.se
