### ISSUE TITLE
Error: cannot create note because it is empty.

### ISSUE THREAD

**Issue by hettsuke** [Ajatt-Tools/mpvacious#2]
Platform: Windows
running on the newest version of mpv

Hey, the script seems to work just fine with the exception that I can't generate any cards.
Whenever I try to do so I get the Error "cannot create note because it is empty."

**Comment by rentatsumoto** [comment]
It might be due to wrong order of fields in the note type.
```
Sentence field should be first in the note type settings. Otherwise Anki won't allow mpvacious to add new notes.
```

**Comment by hettsuke** [comment]
Fixed. 
I initially had it that way but I had to fix another mistake of mine (empty question side), resulting in me changing the note type to one where that wasn't the case anymore.

Thanks!
