### ISSUE TITLE
Feature request: secondary subtitle

### ISSUE THREAD

**Issue by juligreen** [Ajatt-Tools/mpvacious#21]
After this pull request gets merged: https://github.com/mpv-player/mpv/pull/8462 , mpv can include a secondary subtitle in hidden mode.

Could mpvacious then export anki cards that include the translation of a line?

**Comment by tatsumoto-ren** [comment]
Relying on native language translation goes agains AJATT.

Nevertheless it would be possible to introduce this feature as soon as mpv lua API provides an interface for doing it.

**Comment by markhavemann** [comment]
+1

Definitely not something I would want for most cards but for the odd sentence that means something slightly different than you thought it should, this could be useful

**Comment by tatsumoto-ren** [comment]
Cool, looking forward for pull requests.
