### ISSUE TITLE
Clipboard Auto Copy

### ISSUE THREAD

**Issue by Jarods-language-journey** [Ajatt-Tools/mpvacious#25]
>Before making a new issue please seek help in the [matrix chat](https://app.element.io/#/room/#djt:g33k.se). Thank you.

**Environment:**
 - OS: Windows 10
 - Latest windows 10
 - Latest mpv version - 0.33.0 (2-28-21)

**Describe the bug**
Clipboard auto copy does not work correctly.  This happened after playing around with youtube-dl and trying to get VRV to play through mpv

The only things that changed were downloading youtube-dl and adding these to the mpv config file.
Code passed: (commented out atm)
#ytdl-raw-options=username=user,password=pass
#ytdl-raw-options=format=best[format_id!*=hardsub]

I've figured out that everytime I try to pass arguments to ytdl it breaks my mpv so I tried removing the code but I still have the same issue.

The only time clipboard auto copy works correctly is when playing on from quick access, if any subsequent link or file is dragged into the current mpv it will work correctly

 If I open up the file from anywhere that is not from quick access, will not automatically copy to the clipboard.

**To Reproduce**
1. Put those lines of code in mpv.conf file
2. Open up some video into mpv (cmd or exe)
3. Drag subtitles onto video
4. Enable mpvacious as normal
5. Observe yomichan clipboard monitor

**Expected behavior**
Clipboard auto copying

**Screenshots**
Link to a youtube video demonstrating the problem
https://www.youtube.com/watch?v=C4njG0nHOa8

**Comment by tatsumoto-ren** [comment]
Windows is tricky. Do you get any error messages in the logs (accessed by pressing `~` in mpv)?

**Comment by Jarods-language-journey** [comment]
None that are too tricky.  I do get the following:

```
C:\Users\jarod\AppData\Roaming/mpv/mpv.conf:3: unparseable extra characters: ':jpn,jp,en'
C:\Users\jarod\AppData\Roaming/mpv/mpv.conf:4: unparseable extra characters: ':jpn,jp,en'
```

But I've commented those lines out and still had the same issue. 

If I may, I tried it both with an older version of mpvacious along with the newer one that you released as well.

**Comment by Jarods-language-journey** [comment]
Here's the bootup when I launch it with CMD for the same file

```
[autoload] Adding Re_Zero_2.mkv
[autoload] Adding Re_Zero_3.mkv
[autoload] Adding Re_Zero_4.mkv
[autoload] Adding Re_Zero_5.mkv
[autoload] Adding Re_Zero_6.mkv
[autoload] Adding Re_Zero_7.mkv
[autoload] Adding Re_Zero_8.mkv
[autoload] Adding Re_Zero_9.mkv
[autoload] Adding Re_Zero_10.mkv
[autoload] Adding Re_Zero_11.mkv
[autoload] Adding Re_Zero_12.mkv
[autoload] Adding Re_Zero_13.mkv
[autoload] Adding Re_Zero_14.mkv
[autoload] Adding Re_Zero_15.mkv
[autoload] Adding Re_Zero_16.mkv
[autoload] Adding Re_Zero_17.mkv
[autoload] Adding Re_Zero_18.mkv
[autoload] Adding Re_Zero_19.mkv
[autoload] Adding Re_Zero_20.mkv
[autoload] Adding Re_Zero_21.mkv
[autoload] Adding Re_Zero_22.mkv
[autoload] Adding Re_Zero_23.mkv
[autoload] Adding Re_Zero_24.mkv
[autoload] Adding Re_Zero_25.mkv
[autoload] Adding Re_Zero_26.mkv
[autoload] Adding Re_Zero_27.mkv
[autoload] Adding Re_Zero_28.mkv
[autoload] Adding Re_Zero_29.mkv
[autoload] Adding Re_Zero_30.mkv
[autoload] Adding Re_Zero_31.mkv
[autoload] Adding Re_Zero_32.mkv
[autoload] Adding Re_Zero_33.mkv
[autoload] Adding Re_Zero_34.mkv
[autoload] Adding Re_Zero_35.mkv
[autoload] Adding Re_Zero_36.mkv
[autoload] Adding Re_Zero_37.mkv
[autoload] Adding Re_Zero_38.mkv
 (+) Video --vid=1 (*) (hevc 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (vorbis 2ch 48000Hz)
 (+) Subs  --sid=1 'Re_Zero_1.srt' (subrip) (external)
     Subs  --sid=2 'Re_Zero_10.srt' (subrip) (external)
     Subs  --sid=3 'Re_Zero_11.srt' (subrip) (external)
     Subs  --sid=4 'Re_Zero_12.srt' (subrip) (external)
     Subs  --sid=5 'Re_Zero_13.srt' (subrip) (external)
     Subs  --sid=6 'Re_Zero_14.srt' (subrip) (external)
     Subs  --sid=7 'Re_Zero_15.srt' (subrip) (external)
     Subs  --sid=8 'Re_Zero_16.srt' (subrip) (external)
     Subs  --sid=9 'Re_Zero_17.srt' (subrip) (external)
     Subs  --sid=10 'Re_Zero_18.srt' (subrip) (external)
     Subs  --sid=11 'Re_Zero_19.srt' (subrip) (external)
File tags:
 Title: [ShowY] Re Zero Kara Hajimeru Isekai Seikatsu - 01 The End of the Beginning and the Beginning of the End
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p10
AV: 00:00:00 / 00:50:01 (0%) A-V:  0.001 Dropped: 4
[subs2srs] Deck subs2srs: check completed.
(Paused) AV: 00:00:04 / 00:50:01 (0%) A-V:  0.000 Dropped: 6
[subs2srs] Clipboard autocopy has been enabled.
(Paused) AV: 00:00:04 / 00:50:01 (0%) A-V:  0.000 Dropped: 6
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'clip' is not recognized as an internal or external command,
operable program or batch file.
(Paused) AV: 00:00:06 / 00:50:01 (0%) A-V:  0.000
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'clip' is not recognized as an internal or external command,
operable program or batch file.
AV: 00:00:10 / 00:50:01 (0%) A-V:  0.000
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'clip' is not recognized as an internal or external command,
operable program or batch file.
AV: 00:00:21 / 00:50:01 (1%) A-V: -0.000
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'clip' is not recognized as an internal or external command,
operable program or batch file.
AV: 00:00:24 / 00:50:01 (1%) A-V: -0.000
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'clip' is not recognized as an internal or external command,
operable program or batch file.
AV: 00:00:48 / 00:50:01 (2%) A-V:  0.000
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'clip' is not recognized as an internal or external command,
operable program or batch file.
(Paused) AV: 00:00:49 / 00:50:01 (2%) A-V:  0.000
Saving state.

Exiting... (Quit)
```

**Comment by tatsumoto-ren** [comment]
> 'chcp' is not recognized as an internal or external command, operable program or batch file.
> 'clip' is not recognized as an internal or external command, operable program or batch file.

This is interesting. I wonder why it happened.

**Comment by tatsumoto-ren** [comment]
Is your PATH modified? system32 should always be in PATH but apparently for you it's not. There are a few [guides](https://helpdeskgeek.com/how-to/fix-not-recognized-as-an-internal-or-external-command/) on google that aim to help with this, but I don't use Windows and can't test them.

**Comment by Jarods-language-journey** [comment]
Damn, I must've deleted my system32 while modifying my paths for different exe files.  Once I put it back into my path, everything works!  Now I can post my damn YouTube video on how to get MPV running with VRV.

![image](https://user-images.githubusercontent.com/80096108/110190820-20b4e280-7dda-11eb-9658-29a48386e052.png)

Thank you for helping me out with my oversight!  I'm still a beginner in this area but am always learning!

**Comment by tatsumoto-ren** [comment]
No problem, glad that we've figured this out!
