### ISSUE TITLE
mpvacious breaks input-ipc-server

### ISSUE THREAD

**Issue by CarlosMFdz** [Ajatt-Tools/mpvacious#27]
**Environment:**
 - OS: Arch Linux
 - Linux 5.11.5-arch1-1
 - mpv 0.33.0-dirty

**Describe the bug**
I rely on mpv's input-ipc-server option for some personal scripts, but it seems that using mpvacious breaks this functionality. As far as I know mpvacious doesn't use the ipc server at all so I have no idea why it breaks, but somehow it does.

**To Reproduce**
1. Make sure the ipc server works under normal circumstances by disabling mpvacious (subs2srs.lua.disable)
2. add "input-ipc-server=/tmp/mpv.socket" to mpv.conf
3. start mpv and run the following in a terminal (make sure you have socat installed)
``echo '{"command":["show-text","This is a message"]}' | socat - /tmp/mpv.socket``
4. if everything is working you should get "This is a message" in the mpv window.
5. Now enable mpvacious again
6. start mpv and run the command above once again
7. You will get the following output
``socat[98709] E connect(5, AF=1 "/tmp/mpv.socket", 17): Connection refused``

**Expected behavior**
"This is a message" in the mpv window

**Comment by tatsumoto-ren** [comment]
I use the `input-ipc-server` feature every day but so far it has worked without any issues. You may want to look at [this add-on](https://github.com/wis/mpvSockets) to handle your sockets.

**Comment by CarlosMFdz** [comment]
Unfortunately for some of my used I need a fixed path so mpvSockets doesn't help, but I guess tha's not something that can be solved here.

**Comment by emiham** [comment]
There's definitely something weird happening here. Other scripts that use the socket seem to work, but `socat` doesn't. 

Also you can run mpv with `mpv --input-ipc-server=/tmp/mpv.socket`, and as long as it's not also defined in your `mpv.conf` the socket should now work.
