### ISSUE TITLE
script-binding mpvacious-update-last-note not working

### ISSUE THREAD

**Issue by danielhuangsw** [Ajatt-Tools/mpvacious#28]
**Environment:**
 - OS: Ubuntu 18.04 LTS
 - mpv version: 0.33.0 

**Describe the bug**
I've binded `Ctrl+m script-binding mpvacious-update-last-note` in mpv input.conf. When I tried to use that `Ctrl+m` on mpv, the note is updated but with no sound file and no picture file.

alternative workflow of pressing `a` then `m` will achieve the same result and it is working on my machine.

**To Reproduce**
1. press Ctrl+m on currently visible subtitle line on the front
2. anki browse window pop out

**Expected behavior**
note created with sound file and picture file.

**terminal output**
```
[mpvacious] Note #1615893229052 updated. 
(Paused) AV: 00:09:51 / 00:23:47 (41%) A-V:  0.000
[modules] Note #1615893229052 updated. 
(Paused) AV: 00:09:51 / 00:23:47 (41%) A-V:  0.000
A: 00:09:53 / 00:23:47 (42%) {0.0min 11.50x 0.0MB}
A: 00:09:53 / 00:23:47 (42%) {0.0min 10.15x 0.0MB}
[mpvacious] File stored: 'MushokuTenseiIsekaiIttaraHonkiDasuS01E10_09m51s658ms-09m53s908ms.ogg'. 
(Paused) AV: 00:09:51 / 00:23:47 (41%) A-V:  0.000
[modules] Couldn't store file 'MushokuTenseiIsekaiIttaraHonkiDasuS01E10_09m51s658ms-09m53s908ms.ogg': [Errno 2] No such file or directory: '/tmp/MushokuTenseiIsekaiIttaraHonkiDasuS01E10_09m51s658ms-09m53s908ms.ogg' 
[mpvacious] File stored: 'MushokuTenseiIsekaiIttaraHonkiDasuS01E10_09m51s716ms.jpg'. 
[modules] Couldn't store file 'MushokuTenseiIsekaiIttaraHonkiDasuS01E10_09m51s716ms.jpg': [Errno 2] No such file or directory: '/tmp/MushokuTenseiIsekaiIttaraHonkiDasuS01E10_09m51s716ms.jpg' 
```

**Comment by tatsumoto-ren** [comment]
I tried to reproduce it but couldn't, everything worked. So I don't know what else to say.

**Comment by danielhuangsw** [comment]
I see. Thanks for the help!
Since the root of the issue is unknown we can close this issue for now.
