### ISSUE TITLE
mpvacious crash when press m to update Yomichan'ed card

### ISSUE THREAD

**Issue by HQYang1979** [Ajatt-Tools/mpvacious#30]
>Before making a new issue please seek help in the [matrix chat](https://app.element.io/#/room/#djt:g33k.se). Thank you.

**Environment:**
 - OS: Win10
 - OS version
 - mpv version: 20210316

**Describe the bug**
A description of what the bug is.
mpvacious automatically crashed when press m to update yomichan'ed card...

**To Reproduce**
1. Press m to update Yomichan'ed card
2. mpvacious exited, no appearance when press a.

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Comment by tatsumoto-ren** [comment]
Should be fixed in 7c9de23c5c57b4e8083cd738357ebb85beca3572.
