### ISSUE TITLE
mpvacious note type PRs?

### ISSUE THREAD

**Issue by cyphar** [Ajatt-Tools/mpvacious#33]
I've made some changes to the mpvacious note type that I think could be quite helpful:

* I made it so the pitch accent colouring isn't shown on the front -- instead the target word has a faint border added. This is nice because it means you can try to recall the pitch accent rather than having it told to you immediately.
* I added a separate `VocabDefMonolingual` field which is useful for folks starting the monolingual transition. If the field is used, the bilingual `VocabDef` field is displayed using `{{hint:...}}` which means you can focus on trying to read the monolingual definition before you see the bilingual one.

Unfortunately it seems the mpvacious note type source code is only available through AnkiWeb where I can't send a PR -- I'd be happy to send a PR with these changes (if you're interested) but it seems there's nowhere for me to send it. It is possible to have the source available in this repo so folks can contribute to it (and you can then push to AnkiWeb at whatever interval suits you best)? Thanks.

For reference this is what my new notes look like:

<details>
<summary>Front</summary>

![2021-04-20-014651_772x93_scrot](https://user-images.githubusercontent.com/2888411/115265218-5ccdb800-a17a-11eb-9704-3aa626578aff.png)

</details>

<details>
<summary>Back</summary>

![2021-04-20-014712_1123x642_scrot](https://user-images.githubusercontent.com/2888411/115265220-5dfee500-a17a-11eb-8551-a67a64ff43c5.png)

</details>

**Comment by tatsumoto-ren** [comment]
It is a good idea, though currently we don't have any system at all that would allow the users to share their note type settings, so it has to be established. Most users have their own note types that they never share.

I think storing settings in a different repo and linking it here would be great.

**Comment by tatsumoto-ren** [comment]
Now we have a separate repo with user-created note types. You can browse it [here](https://github.com/Ajatt-Tools/AnkiNoteTypes). 

I'm going to link it in the readme.

**Comment by cyphar** [comment]
Awesome, I'll submit my note-type there then. :D
