### ISSUE TITLE
osd_styler not found

### ISSUE THREAD

**Issue by toprak** [Ajatt-Tools/mpvacious#34]
**Environment:**
 - OS: Ubuntu
 - 20.04
 - mpv 0.33.0

**Describe the bug**
I just did `mpv anime.mkv` and got [that](https://paste.ubuntu.com/p/4xVwyGBXwZ/)

**To Reproduce**
mpv videoname is enough.
**Expected behavior**
Work properly.

**Comment by toprak** [comment]
I just deleted modules.lua and it seems it works now. I will reopen that issue if it would show up again.

**Comment by tatsumoto-ren** [comment]
Come to think of it, it is okay to delete the note about `modules.lua` fom the readme because mpv v0.33 came out many months ago.

**Comment by toprak** [comment]
Ye agreed.
