### ISSUE TITLE
Addon doesn't working.

### ISSUE THREAD

**Issue by AngeloBenjamin0** [Ajatt-Tools/mpvacious#35]
>Before making a new issue please seek help in the [matrix chat](https://app.element.io/#/room/#djt:g33k.se). Thank you.

**Environment:**
 - OS: Windows
 - OS version
 - mpv version mpv-x86_64-20210404-git-dd86f19

**Describe the bug**
I installed the addon following the instructions and the it doesn't work. I found something in the mpv console that maybe useful to know what's happening.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/82250378/116139615-96d41800-a6ac-11eb-82d8-3fba05dac782.png)

**Comment by tatsumoto-ren** [comment]
Please, follow the installation instructions correctly. all *lua files of the addon should be all in one folder.

**Comment by AngeloBenjamin0** [comment]
All of the *lua files of the addon are in the scripts folder.
![imagen](https://user-images.githubusercontent.com/82250378/116147086-aa37b100-a6b5-11eb-8115-293befe3d86a.png)

**Comment by tatsumoto-ren** [comment]
but why aren't they placed in their own folder, like it says in the readme?
```
~/.config/mpv/scripts
|-- other_addon_1
|-- other_addon_2
`-- mpvacious
    |-- main.lua
    |-- ...
    `-- subs2srs.lua
```

**Comment by SecondaryH** [comment]
`C:/Users/Username/AppData/Roaming/mpv/scripts/`

Your scripts folder should look like this

![image](https://user-images.githubusercontent.com/76407423/116288590-f48e6000-a791-11eb-820a-7a727b6ef69c.png)

Try reinstalling and then simply download the latest zip and extract it or git clone if you're using git bash

**Comment by AngeloBenjamin0** [comment]
Sorry, I didn't completly understood the installation instructions. I extracted the folder in the scripts folder and everything is working now. Thanks.

**Comment by tatsumoto-ren** [comment]
Glad it works now.
