### ISSUE TITLE
Fix installation instructions for mpv 0.32

### ISSUE THREAD

**Issue by skangas** [Ajatt-Tools/mpvacious#38]
In #34, it seems like a note about modules.lua was removed (8b10b63). Please consider re-adding it.

The next version of Debian GNU/Linux (which will be the next stable version for the next 2-3 years) [is shipping mpv 0.32](https://packages.debian.org/bullseye/mpv).

I just ran into this issue and it would have saved me ~30 minutes not to have to go look for this.

BTW, the old note did not work for me. I git cloned the mpvacious repository into `~/.config/mpv/mpvacious` and had to put the following into `modules.lua` to get it to work:

```
local home = os.getenv("HOME")
package.path = package.path .. ';' .. home .. '/.config/mpv/scripts/mpvacious/?.lua'

local mpv_scripts_dir_path = os.getenv("HOME") ..  "/.config/mpv/scripts/"
function load(relative_path) dofile(mpv_scripts_dir_path .. relative_path) end
load("mpvacious/subs2srs.lua")
```

Thanks!

**Comment by tatsumoto-ren** [comment]
Why is `package.path` needed here? I don't see the variable being used.

**Comment by skangas** [comment]
This is to set up the LUA load path for require. Without that line I get:

```
[modules] Lua error: /home/fuchi/.config/mpv/scripts/subs2srs/subs2srs.lua:82: module 'osd_styler' not found:
[modules] 	no field package.preload['osd_styler']
[modules] 	no file '/usr/local/share/lua/5.2/osd_styler.lua'
[modules] 	no file '/usr/local/share/lua/5.2/osd_styler/init.lua'
[modules] 	no file '/usr/local/lib/lua/5.2/osd_styler.lua'
[modules] 	no file '/usr/local/lib/lua/5.2/osd_styler/init.lua'
[modules] 	no file '/usr/share/lua/5.2/osd_styler.lua'
[modules] 	no file '/usr/share/lua/5.2/osd_styler/init.lua'
[modules] 	no file '/usr/local/lib/lua/5.2/osd_styler.so'
[modules] 	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/osd_styler.so'
[modules] 	no file '/usr/lib/lua/5.2/osd_styler.so'
[modules] 	no file '/usr/local/lib/lua/5.2/loadall.so'
```
