### ISSUE TITLE
mpvacious_linux_v0.2.lua:325: '=' expected near 'ret'

### ISSUE THREAD

**Issue by harkdand** [Ajatt-Tools/mpvacious#4]
I receive this error with the latest release:
```
11220 ~ $ mv dls/mpvacious_linux_v0.2.lua .config/mpv/scripts/
11220 ~ $ mpv pix/ani/hyouka/Hyouka\ -\ 01.mkv
[mpvacious_linux_v0_2]
[mpvacious_linux_v0_2] stack traceback:
[mpvacious_linux_v0_2]  [C]: ?
[mpvacious_linux_v0_2]  [C]: ?
[mpvacious_linux_v0_2] Lua error: /home/<user>/.config/mpv/scripts/mpvacious_linux_v0.2.lua:325: '=' expected near 'ret'
```
I have all dependencies listed in the readme and mpv version 0.32.0.

**Comment by tatsumoto-ren** [comment]
Thank you for the bug report. It's really strange but I can't get the same error. It must be platform-specific or related to the version of lua that mpv uses. Does it work with [this file](https://pastebin.com/raw/Yck6PeDh)?

**Comment by harkdand** [comment]
Thanks for the quick response! The file you sent fixes the error on startup! However, Ctrl+C to copy subs doesn't work for me and throws this error:
```
[new_mpvvacious]
[new_mpvvacious] stack traceback:
[new_mpvvacious]        /home/<user>/.config/mpv/scripts/new_mpvvacious.lua:169: in function 'copy_to_clipboard'
[new_mpvvacious]        /home/<user>/.config/mpv/scripts/new_mpvvacious.lua:175: in function 'fn'
[new_mpvvacious]        mp.defaults:225: in function 'fn'
[new_mpvvacious]        mp.defaults:60: in function 'handler'
[new_mpvvacious]        mp.defaults:365: in function 'handler'
[new_mpvvacious]        mp.defaults:486: in function 'call_event_handlers'
[new_mpvvacious]        mp.defaults:520: in function 'dispatch_events'
[new_mpvvacious]        mp.defaults:479: in function <mp.defaults:478>
[new_mpvvacious]        [C]: ?
[new_mpvvacious]        [C]: ?
[new_mpvvacious] Lua error: /home/<user>/.config/mpv/scripts/new_mpvvacious.lua:169: attempt to index a boolean
value
```
Lua Version: `Lua 5.1.5`
OS: Gentoo

**Comment by tatsumoto-ren** [comment]
>Lua 5.1.5

This must be it. mpv by default uses lua 5.2 and I expect many things to break in older versions.
[This](https://pastebin.com/raw/24vWcLtX) is my attempt to rewrite that chunk with 5.1 support.

**Comment by harkdand** [comment]
This works! I will make sure I'm on 5.2 before reporting any problems on future versions. Thanks!

**Comment by tatsumoto-ren** [comment]
Thank you for your feedback. To support lua 5.1 I'm going to commit the changes.
