### ISSUE TITLE
Generating anki cards fails to store audio clip or image snapshot

### ISSUE THREAD

**Issue by flamesword1123** [Ajatt-Tools/mpvacious#43]
<img width="1201" alt="Screen Shot 2021-06-12 at 10 49 08 PM" src="https://user-images.githubusercontent.com/13880644/121793765-6995e780-cbd0-11eb-9c95-a76ba6b00a5d.png">
**Environment:**
 - OS: MacOS Catalina
 - Ver. 10.15.7
 - mpv 0.33.1

**Describe the bug**
Exporting anki cards with audio or an image snapshot from mpv results in a new card being created but with a nonexistent image named snapshot and an audio file that is correctly named but totally empty and doesn't play anything (see screenshot below). Checking media through anki shows that both the snapshot and audio are missing. The mpv console shows two errors saying: 
" Couldn't store file 'HorimiyaS01E02_01m16s994ms.jpg': [Errno 2] No such file or directory: '/tmp/HorimiyaS01E02_01m16s994ms.jpg' " and 
" Couldn't store file 'HorimiyaS01E02_01m15s580ms-01m17s790ms.mp3': [Errno 2] No such file or directory: '/tmp/HorimiyaS01E02_01m15s580ms-01m17s790ms.mp3' "
It seems like saving these files to a temporary directory before sending them to the anki collection isn't working since they are never making it to the collection.media folder. When I make a card with yomichan and ankiconnect the audio is saved normally so I think it's an mpvacious specific issue. I've reinstalled mpvacious and mpv and the only changes I've made to the config within subs2srs.lua are to set up the deck, note type, and fields. Any help on this issue would be much appreciated. 

**To Reproduce**
1. Press control control-e in mpv with a video file open. 
2. Go to anki and find the generated card.
3. See error

**Screenshots**
<img width="655" alt="Screen Shot 2021-06-12 at 10 43 45 PM" src="https://user-images.githubusercontent.com/13880644/121793686-a6adaa00-cbcf-11eb-9963-53f9b117dd9e.png">

<img width="439" alt="Screen Shot 2021-06-12 at 10 44 17 PM" src="https://user-images.githubusercontent.com/13880644/121793695-b9c07a00-cbcf-11eb-8efe-23e1cc39bdce.png">

**Comment by tatsumoto-ren** [comment]
Media creation depends on mpv's built-in encoder. In some versions of mpv it may be missing, which is most likely why this error occurs for some users. In the readme you can find instructions for checking whether your version of mpv has the encoder or not.

**Comment by tatsumoto-ren** [comment]
I'm going to copy the instructions here. 

Try running this command in a terminal.
```
$ mpv 'test_video.mkv' --loop-file=no --frames=1 -o='test_image.jpg'
```
Replace `test_video.mkv`  with a valid path.

If you get an error, you need to find and install a different build of mpv that has the built-in encoder.

**Comment by flamesword1123** [comment]
Thank you for the quick response. The shell command to test this isn't running for me. It says "command not found: mpv". I wasn't sure if adding mpv to path would make it possible. I had added the /.config/mpv directory to my path variable but I wasn't sure if that was what it meant.

**Comment by tatsumoto-ren** [comment]
The directory containing the `mpv` executable file should be added to `PATH`. On GNU/Linux this is achieved by editing `~/.profile`, I assume the process is similar on a Mac.

**Comment by flamesword1123** [comment]
I was able to run it. This was the output I got:
<img width="1423" alt="Screen Shot 2021-06-12 at 11 33 11 PM" src="https://user-images.githubusercontent.com/13880644/121794489-8df4c280-cbd6-11eb-9101-25ef28ad787c.png">

**Comment by tatsumoto-ren** [comment]
If you have the image generated successfully, media generation should work fine from now on as long as you keep mpv in PATH.

**Comment by flamesword1123** [comment]
I just checked. It works great now. Thanks so much for your help!
