### ISSUE TITLE
Unable to store screenshots and audio clips [Errno 2] 

### ISSUE THREAD

**Issue by giulio-greco** [Ajatt-Tools/mpvacious#44]
**Environment:**
 - OS Fedora 34
 - mpv version 0.33.1
 - Anki flatpak 
 - wayland (probably irrelevant)
 - [mpv config](https://pastebin.ubuntu.com/p/C9zpMBzWpD/)

**Describe the bug**
mpvacious can't store files while updating anki cards created via yomichan, i also tried changing: `self.tmp_dir = function()
        return '/tmp'` to `self.tmp_dir = function() return '/home/giuji/.tmp'` , ` mpv 'test_video.mkv' --loop-file=no --frames=1 -o='test_image.jpg'` works on my machine

**To Reproduce**
1. Open a video file and enable autocopy via mpvacious menu
2. Create a new card using yomichan 
3. Update the note by pressing c + m in the mpvacious menu
4. Preview the card
5. Check mpv logs

**Expected behavior**
Anki card gets updated with screenshot and audio clip but no actual file gets created. mpv logs: `[  19.094][e][mpvacious] Couldn't store file '響け！ユーフォニアム01_16m35s489ms-16m37s399ms.ogg': [Errno 2] No such file or directory: '/tmp/響け！ユーフォニアム01_16m35s489ms-16m37s399ms.ogg' `

**Screenshots**
![Screenshot from 2021-06-19 17-24-04](https://user-images.githubusercontent.com/64275280/122647205-95562780-d112-11eb-8f14-5b27b340b30f.png)
![Screenshot from 2021-06-19 17-23-23](https://user-images.githubusercontent.com/64275280/122647210-98e9ae80-d112-11eb-8215-82fe91c16deb.png)
![Screenshot from 2021-06-19 17-26-28](https://user-images.githubusercontent.com/64275280/122647232-ba4a9a80-d112-11eb-9d8c-1470c25592dc.png)

PS: this is the first time I report an issue on github, help me if I've done something wrong

**Comment by tatsumoto-ren** [comment]
> mpvacious can't store files while updating anki cards created via yomichan

Does it work if you change screenshot format to jpg?

> self.tmp_dir

That is unlikely to be the cause, unless you don't have /tmp on your machine for some reason.

> To Reproduce

I can't reproduce so I can't pinpoint anything in particular.
For example, try [videoclip](https://github.com/Ajatt-Tools/videoclip).
Internally it works almost the same way as mpvacious.
If `videoclip` doesn't work for you, you might have an incompatible build of mpv installed.

> this is the first time I report an issue on github, help me if I've done something wrong

There's no need to, you could simply ask in our chat.

**Comment by aramrw** [comment]
The same thing happens for me on Windows, audio works but the picture is just like in that screenshot

**Comment by tatsumoto-ren** [comment]
@aramrw you need to restart anki in this case.

**Comment by aramrw** [comment]
> @aramrw you need to restart anki in this case.

o damn that was simple thanks 👍🏼
