### ISSUE TITLE
Bind for switching output deck

### ISSUE THREAD

**Issue by yaoberh** [Ajatt-Tools/mpvacious#47]
Hey!
Would be cool if one could change the output deck with a shortcut. For people like me who are learning different things in different profiles.

**Comment by tatsumoto-ren** [comment]
Nice idea! Are you going to implement it?

**Comment by yaoberh** [comment]
I would gladly, but I'm not a programmer...It's just an idea I had :)

**Comment by tatsumoto-ren** [comment]
Alright. I'm going to work on it then.

**Comment by tatsumoto-ren** [comment]
I have implemented support for profiles. The explanation is available [here](https://github.com/Ajatt-Tools/mpvacious#profiles). Feel free to test it.

**Comment by yaoberh** [comment]
Wow! Works perfectly. This is such a cool addition...Thanks a lot :)
