### ISSUE TITLE
Menu to access Mpvacious doesn't function anymore.

### ISSUE THREAD

**Issue by eme35** [Ajatt-Tools/mpvacious#48]
Hello,

I apologize for creating a ticket for this small issue since i can't find an answer for this on YouTube or anywhere else, when i installed your Mpvacious script the key to access the menu ''A'' doesn't do anything anymore, a year ago when i first started using your script and Mpv Player it worked fine, also when i press the T key it just simply nudges the subtitle alittle, do you know what i am doing wrong? i've also tried to download and use a older version of MPV but the same issue still happens.

Kind regards

**Comment by tatsumoto-ren** [comment]
Make sure you follow the installation instructions in the README.md file.

**Comment by eme35** [comment]
Hello,

I red the README file in the ZIP and it's mentioning that there is a conf file inside mpv in %appdata% directory but i don't have such file, i tried searching the github page of MPV and it has a input folder with a couple of files in it but those don't include the keybinds.

**Comment by tatsumoto-ren** [comment]
It's okay for config files to not exist. They have to be created on demand. Usually mpv.conf and input.conf are not strictly necessary. When it comes to subs2srs.conf which is a config file for mpvacious, it is stored at `C:/Users/Username/AppData/Roaming/mpv/script-opts/subs2srs.conf` in case of a windows machine.

https://github.com/Ajatt-Tools/mpvacious#configuration

When installing the add-on make sure to unzip the entire folder to `C:/Users/Username/AppData/Roaming/mpv/scripts/` as shown in the "directory structure" graph.

https://github.com/Ajatt-Tools/mpvacious#installation

**Comment by eme35** [comment]
Extracting the entire ZIP file into the MPV folder at %appdata% has solved the issue, thank you very much! I was getting worried that i wouldn't be able to solve this issue because i really like MPV and its functionalities. I will also update my YouTube comment with this fix for people who might encounter the same problem.
