### ISSUE TITLE
Words do not have spaces in Danish language

### ISSUE THREAD

**Issue by Digital-Coder** [Ajatt-Tools/mpvacious#49]
1) OS name windows
2) OS version 10 
3) mpv version newest

**Describe the bug**
Clipboard autocopy does not make spaces in Danish language. words are squeezed sometimes.
This is what I get using texthooker.com
![Capture](https://user-images.githubusercontent.com/31192965/130611386-412247af-b848-44cb-be75-60bc78ec1744.PNG)

**Expected behavior**
this is expected copied text from tv series
![Capture2](https://user-images.githubusercontent.com/31192965/130611582-ab377cb6-9d78-4fb4-9234-15092f36b84e.PNG)

**To Reproduce**
load danish subs, enable autocopy, use texthooker.com to see the results

**Comment by tatsumoto-ren** [comment]
Maybe you need to set `nuke_spaces` to `no` in the [config file](https://github.com/Ajatt-Tools/mpvacious/blob/master/.github/RELEASE/subs2srs.conf#L43).

**Comment by Digital-Coder** [comment]
Thank you @tatsumoto-ren  !! it worked !. For others, I had to create subs2srs.conf in `C:/Users/Username/AppData/Roaming/mpv/script-opts/` folder and add `nuke_spaces=no`
