### ISSUE TITLE
Feature Request | Option to switch audio from .ogg to IOS compatible container

### ISSUE THREAD

**Issue by harkdand** [Ajatt-Tools/mpvacious#5]
The Anki IOS app throws this error when playing an mpvacious generated card:

![anki-ios](https://user-images.githubusercontent.com/35568778/96390390-a01a8000-1171-11eb-82e2-0d468f3574c9.jpg)

**Comment by tatsumoto-ren** [comment]
> iOS doesn't support ogg/opus

Oh that's bad. I think we could fix that by adding another config option that switches between opus and mp3.

**Comment by harkdand** [comment]
Unrelated but they also refuse to support VP8/9 so no webms either :/

**Comment by tatsumoto-ren** [comment]
I've pushed the changes to [master](https://raw.githubusercontent.com/Ajatt-Tools/mpvacious/master/subs2srs.lua). If you add `audio_format=mp3` to the config file, the add-on will use mp3 for encoding.

> VP8/9

Currently `libwebp` is used to encode images (as with `opus`, it saves a lot of disk space). Does iOS fail to display it too? 

PS: I use AnkiDroid, and it has no problems with both `libwebp` and `libopus`.

**Comment by harkdand** [comment]
Works like a charm! Does the `audio_bitrate=` parameter have any effect on the mp3 files?

I was also expecting webp to not work because its based on VP8/9 but I guess Apple had to bite the bullet cause a lot of sites would break. The decoding problem is not with the Anki app itself, but in that the Anki app uses the native IOS video/audio player which doesn't support webm or ogg. (There are third party IOS apps that do though).

**Comment by tatsumoto-ren** [comment]
> Does the `audio_bitrate=` parameter have any effect on the mp3 files?

Yes, but it's impossible to set it lower than 32k, it'll just default to 32k anyways.

**Comment by harkdand** [comment]
Thanks a bunch once again!

**Comment by tatsumoto-ren** [comment]
Thank you too for letting know about the bug.
