### ISSUE TITLE
Installation for Celluloid does not work

### ISSUE THREAD

**Issue by k-kirill** [Ajatt-Tools/mpvacious#53]
I cannot install the script for Celluoid 0.21 as just dropping all the `*.lua` files into the Plugins tab no longer works.
Nor does putting them all into a separate directory inside `~/.config/celluloid/scripts`.

Could you please update the instructions to install the script for Celluloid?

**Comment by tatsumoto-ren** [comment]
It's been a while since I used Celluoid. How do you install the scripts on it? I'm guessing copying the folder to `~/.config/celluloid/scripts` should work though.

**Comment by k-kirill** [comment]
I found some lua script and was able to modify it to make mpvacious work with Celluloid :) With it in the `scripts` folder it can load everything from the checked out `mpvacious` directory.
```
local mpv_scripts_dir_path = os.getenv("HOME") ..  "/.config/celluloid/scripts/"
package.path = package.path .. ';' .. os.getenv("HOME") .. '/.config/celluloid/scripts/mpvacious/?.lua'
function load(relative_path) dofile(mpv_scripts_dir_path .. relative_path) end 
load("mpvacious/subs2srs.lua")
```
