### ISSUE TITLE
Multi-line subtitles are not copying into clipboard

### ISSUE THREAD

**Issue by Cak3lies** [Ajatt-Tools/mpvacious#6]
**Environment:**
 - OS: Windows 10
 - OS version: 2004
 - mpv version: 0.32.0-759-g67b4a96e45

**Bug:**
Subtitles with line breaks are not copied onto the clipboard. For example, this dialogue in an srt file:
``` srt
1
00:00:05,371 --> 00:00:08,404
私のアツいアイドル活動！
“アイカツ！”
```

When copied, the clipboard does not change, and the first line "leaks" into the verbose log.
```
Active code page: 65001
私のアツいアイドル活動！
[statusline] (Paused) AV: 00:00:03 / 00:24:26 (0%) A-V:  0.000 DS: 4.000/0
```
However, remove the line break and it copies successfully.

**Comment by tatsumoto-ren** [comment]
Let's just remove newlines, should work.

**Comment by Cak3lies** [comment]
Works for me, much thanks for the quick fix.

**Comment by tatsumoto-ren** [comment]
Great! Thank you for the bug report.
