### ISSUE TITLE
Ubuntu version is not compatible with libwebp?

### ISSUE THREAD

**Issue by rmikedown** [Ajatt-Tools/mpvacious#60]
I downloaded my mpv from here: https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests

Only problem is I can't create snapshot files with mpv because it say it's not compatible with libwebp and my flashcards are showing up without an image. I tried to grab from another PPA and ran into all kinds of complications and problems that typically happens when I mess around with linux :(

Is this a known issue with the ubuntu mpv/mpvacious? Or am I just not finding the most recent version?

**Comment by tatsumoto-ren** [comment]
It's very likely that the version of mpv you have installed misses the support. Try switching to ffmpeg instead and see if the problem goes away.

**Comment by rmikedown** [comment]
Turns out the mpv I downloaded was fine but the script subs2srs.lua has the setting for "use ffmpeg" set to false by default. So you have to go in there and edit it to say "true".
