### ISSUE TITLE
When trying to create a card fails and shows coulnd't find target note

### ISSUE THREAD

**Issue by OltiP2** [Ajatt-Tools/mpvacious#61]
1)Windows 10
2)21h2
3)mpv-x86_64-20211226-git-d92cf77

When i try to create a card by pressing c the m its says 
coulnd't find target note if i try c and n it says ankiconnect is not running
I reinstalled curl but its still dosen't work

**Comment by tatsumoto-ren** [comment]
That's very unfortunate. Try installing Ankiconnect too.

**Comment by OltiP2** [comment]
> That's very unfortunate. Try installing Ankiconnect too.

I already have ankiconnect

**Comment by tatsumoto-ren** [comment]
Okay, so you have:
0) win10
1) ankiconnect
2) mpvacious
3) anki running

And when you try to create a new note, you get an error.

Why do you think it happens? Do you see any error messages in the console?

**Comment by OltiP2** [comment]
Where can i see the error messages and the console

**Comment by tatsumoto-ren** [comment]
Press `~`

**Comment by OltiP2** [comment]
When clicking c then m 
![image](https://user-images.githubusercontent.com/97410429/149030508-490b49c0-e536-45e7-a537-8babc65f2589.png)

**Comment by OltiP2** [comment]
when clicking c then n
![image](https://user-images.githubusercontent.com/97410429/149030972-81c8d5ec-a388-4178-bdd1-d4639d436f5b.png)

**Comment by OltiP2** [comment]
and i also tried the script on a video player that based on mpv called memento it was working but showed this
![image](https://user-images.githubusercontent.com/97410429/149031281-9851ee80-fa41-4773-8e7e-d2a8fb6b28d9.png)

**Comment by tatsumoto-ren** [comment]
You could try finding a different build of mpv. People say this one is good https://sourceforge.net/projects/mpv-player-windows/files/

**Comment by tatsumoto-ren** [comment]
One way to get rid of the warnings would be to switch to ffmpeg in subs2srs.conf.

**Comment by OltiP2** [comment]
i enabled ffmpeg in memento i removed the libopus and libwebp error but i still getting that cant find target note when trying to create i card like in mpv and also i downloaded mpv from that link but in mpv and memento im both getting this error with everything set up anki running and ankiconnect installed

**Comment by OltiP2** [comment]
because the first time i tried mpvacious was on mpv but i got that message you can see the errors on the first 2 pictures

**Comment by tatsumoto-ren** [comment]
Can you create notes with Yomichan? If you've set up everything correctly, and you have Ankiconnect, Yomichan should work. If Yomichan works but mpvacious doesn't then I don't know maybe you're running mpv from a sandbox or something.

**Comment by OltiP2** [comment]
Yes i can but when i click c the m in dosen't work it shows that couldn't find target note and no im running mpv natively no sandbox

**Comment by OltiP2** [comment]
I used my brother school laptop on mpvacious and it worked great but when they gave me one to the exact same for me too when i set it up on my laptop i just didn't work i went to my brothers laptop and it still working but that laptop is running on a lower windows version because they blocked windows update for him for some reason but the laptop its still the exact same

**Comment by OltiP2** [comment]
so that maybe be the reason i don't know

**Comment by tatsumoto-ren** [comment]
Then make sure you can run curl from `cmd` and your AnkiConnect port is set to 8765.

**Comment by OltiP2** [comment]
I checked my AnkiConnect its on port 8765 and i have curl installed
![image](https://user-images.githubusercontent.com/97410429/149068445-b92722b3-738f-4382-acd7-a5534b0fa582.png)

**Comment by tatsumoto-ren** [comment]
I guess that checks all the checkboxes. The next step for you is to look at the source code and try to find where exactly mpvacious fails.

**Comment by OltiP2** [comment]
And how to i do that

**Comment by tatsumoto-ren** [comment]
The relevant code is in `subs2srs.lua`.

Parts to pay attention to are:

1) https://github.com/Ajatt-Tools/mpvacious/blob/master/subs2srs.lua#L840
2) https://github.com/Ajatt-Tools/mpvacious/blob/master/subs2srs.lua#L1204
3) https://github.com/Ajatt-Tools/mpvacious/blob/master/subs2srs.lua#L1110

**Comment by OltiP2** [comment]
The problem i don't know how to code but im gonna try to understand it

**Comment by OltiP2** [comment]
i cannot understand the code i tried but its too complicated

**Comment by tatsumoto-ren** [comment]
It's hard to determine what the problem is when you're the only one who has it. It must be machine-specific.

**Comment by OltiP2** [comment]
I think it should be a windows 10 problem cause like i said my brother has the exact same laptop but pretty old windows like 2 years old so maybe ill try it on linux cause i've been thinking about switching to linux either way

**Comment by OltiP2** [comment]
But i don't know which distro to use for my low end laptop i have a 4 gb ram system im not sure if you have linux but which linux distro works well on more low end laptops

**Comment by OltiP2** [comment]
I thought maybe lubuntu or linux mx cause i heard they are lightweight

**Comment by tatsumoto-ren** [comment]
Manjaro xfce is often recommended for people who haven't used GNU+Linux before.

**Comment by OltiP2** [comment]
I actually fixed it it was because i was running on a proxy server how i fixed it was i add an new windows environment environemt name HTTPS_PROXY and the enviorenemt value http://user:pass@adress:port

**Comment by tatsumoto-ren** [comment]
Glad to hear that.
