### ISSUE TITLE
Audio not playing in anki (tried with both windows and linux)

### ISSUE THREAD

**Issue by rmikedown** [Ajatt-Tools/mpvacious#62]
Basically everything seems to be set up correctly with the mpvacious folder placed in the scripts folder (~/.config/mpv/scripts and %appdata% mpv respectively). mpvacious works like normal -- the clipboard functions, it exports the flashcards to anki just fine, etc.. the only thing is the audio files don't play. There doesn't seem to be anything wrong with anything else so I can't figure out why this issue is happening. I set it up on both ubuntu 21.10 and windows 11 and had the same problem both times.

I've got mpvacious on windows 10 and ubuntu 20.04 on my desktop and laptop and those work fine. So I'm kind of confused about the cause of this.

**Comment by tatsumoto-ren** [comment]
>  the audio files don't play

Would be reasonable to check if they exist.
If the files are not created properly, try enabling ffmpeg in `subs2srs.conf`.

If files exist and play on one computer but not on the other, maybe Anki doesn't sync the media. Toggle syncing in Anki's settings.
