### ISSUE TITLE
when I am trying to copy subtitle line it is copying nothing but question mark's

### ISSUE THREAD

**Issue by ahahjsakhas** [Ajatt-Tools/mpvacious#66]
**Environment**

1) OS name  Windows
2) OS version 7
3) mpv version 0.33.0-376-ge13fe1299d
4) Logs
5) Screenshots, if applicable
![screenshot.png](https://user-images.githubusercontent.com/90492637/160232016-efb58ce6-982a-4772-a00e-83cecd16aa97.png)

**Comment by tatsumoto-ren** [comment]
You need to install GNU+Linux for this to work. 

* Microsoft's Software is Malware https://www.gnu.org/proprietary/malware-microsoft.html
* Our recommended operating systems https://tatsumoto.neocities.org/blog/our-immersion-learning-toolset.html#gnulinux

**Comment by OltiP2** [comment]
Try switching the Windows Locale to Japanese

**Comment by OltiP2** [comment]
Change your encoding on your browser to UTF8
