### ISSUE TITLE
No scripts folder in mpv directory, cant install

### ISSUE THREAD

**Issue by Woolton** [Ajatt-Tools/mpvacious#68]
1) Win 11
3) latest

**Describe the bug**
I did not have an mpv scripts folder, I installed mpv via scoop. I navigated to the directory scoop gave me, and created a scripts folder to see if this would work, but it doesn't. I cannot use the script at all.

**To Reproduce**
Open MPV

**Expected behavior**
proper function

**Comment by OltiP2** [comment]
did you put the folder like this in to the mpv scripts folder
![s](https://user-images.githubusercontent.com/97410429/162604528-b41bda15-ce60-45ca-86e2-07be3cfaac12.PNG)

**Comment by Woolton** [comment]
It worked after removing the files from mpvacious-master

**Comment by tatsumoto-ren** [comment]
Glad it worked.
