### ISSUE TITLE
Clipboard feature not working

### ISSUE THREAD

**Issue by Woolton** [Ajatt-Tools/mpvacious#69]
1) Win 11
2) latest
3) latest

**Describe the bug**
clipboard capture doesn't work

**To Reproduce**
turn on autocopy, or press ctrl+c

**Expected behavior**
subtitle line is copied to clipboard

**Comment by tatsumoto-ren** [comment]
Send any screenshots, logs or other info in the chat.

**Comment by Woolton** [comment]
https://i.imgur.com/zxHQrXc.png

Using a .sub file. I spent some time today experimenting, .srt files appear to copy properly.

**Comment by tatsumoto-ren** [comment]
`.sub` files won't work because they don't contain any text, they contain images. Convert them to `.srt` or to `.ass` first.

**Comment by Woolton** [comment]
Oh okay, I hadn't realized that the sub formats wouldn't contain scannable text. are srt and ass the only supported types, or does it just exclude types with positional info?
