### ISSUE TITLE
Error: 'Couldn't store file'

### ISSUE THREAD

**Issue by Jack-Yak** [Ajatt-Tools/mpvacious#70]
Manjaro 21.2.6
mpv 0.34.1

Log:
![Screenshot_2022-05-30_00-40-36](https://user-images.githubusercontent.com/20047581/170918533-c79ac946-6b4e-40e8-8cb8-8e19c841a493.png)

Exported images and audio clips do not function. Errors occur regardless of whether ffmpeg is set on in the config file.

Tried installing mpvacious manually and through AUR, but both did not work.

**Comment by tatsumoto-ren** [comment]
See [issue.md](https://github.com/Ajatt-Tools/mpvacious/blob/master/.github/ISSUE_TEMPLATE/issue.md)

**Comment by tatsumoto-ren** [comment]
> Couldn't store file

Make sure you don't use flatpak, snap, etc. Install Anki with `pip` or from the AUR: [Installation](https://tatsumoto.neocities.org/blog/setting-up-anki.html#installation)

> model was not found: Japanese sentences

[import the example mining deck](https://tatsumoto.neocities.org/blog/setting-up-anki.html#import-an-example-mining-deck)
