### ISSUE TITLE
Can't Store Image

### ISSUE THREAD

**Issue by Horfenico** [Ajatt-Tools/mpvacious#72]
**Environment**

1) Windows 11
3) Latest mpv version
![image](https://user-images.githubusercontent.com/6257231/177232170-4947fed7-87a0-4176-8450-bf4dd76aca0e.png)

Images do not store for some reason. No problem with audio. I'm using my own custom deck but can't figure out what's wrong. Anki shows "snapshot" in the field I set but there is no actual image 

Every time I try to update an anki card this happens, no problems with other fields.

**Expected behavior**
Expected a picture to show up

**Comment by tatsumoto-ren** [comment]
See [issue.md](https://github.com/Ajatt-Tools/mpvacious/blob/master/.github/ISSUE_TEMPLATE/issue.md)

**Comment by tatsumoto-ren** [comment]
> Images do not store for some reason.

Switch to ffmpeg in settings.

**Comment by Horfenico** [comment]
I did that and it still happens. I spent a good amount of time trying to figure it out but I'm pretty stumped.

**Comment by tatsumoto-ren** [comment]
Add ffmpeg directory to PATH.

**Comment by Horfenico** [comment]
![image](https://user-images.githubusercontent.com/6257231/177257455-68b2b947-79b9-4e21-b0a5-a13fdbdfaa41.png)
I did, still no good.

**Comment by tatsumoto-ren** [comment]
I don't know then. Install GNU+Linux.

* Microsoft's Software is Malware https://www.gnu.org/proprietary/malware-microsoft.html
* Our recommended operating systems https://tatsumoto.neocities.org/blog/our-immersion-learning-toolset.html#gnulinux

**Comment by nbelikov** [comment]
This might be because somehow the path is converted to the ancient 8+3 naming scheme (see `ERICDA~1`), probably due to presence of non-ASCII characters or something like that; and Anki is unable to open it. But this is just a guess.

**Comment by Horfenico** [comment]
I'll maybe try it out on my macbook and see how it goes, or just settle for only audio since that's what's most important. Thanks for the help though!

**Comment by tatsumoto-ren** [comment]
Next time if you want to ask something, ask in the chat.
