### ISSUE TITLE
The Audio From mpvacious does not work when imported to anki on a specific scene.

### ISSUE THREAD

**Issue by ismi-ismi** [Ajatt-Tools/mpvacious#75]
**Environment**

1) OS name: Windows 11
2) OS version: windows 11 ver 10.0.22000
3) MPV version : [mpv-x86_64-20220814-git-b669a20.7z]
4) Logs: dunno how to make em
5) Screenshots, if applicable
[Images 1](https://imgur.com/a/m5qsSgA) [Images 2](https://imgur.com/a/29SwCWG)

**Describe the bug**
for whatever reason, the audio of this specific scene is just blank (images 1). the audio is there (images 2) but I can't play it. so far, only this scene/part has this problem (i have not gone through the whole movie yet). the image, note, and the other thing still work, but the audio cannot be played.

oh and the way that I'm imported this to Anki is: 
>click add expression in yomichan
>press C in MPV and then Press M (to add the audio, image, etc)
it works for every other scene but this one

**To Reproduce**
My Version of End Of Evangelion is the [Hachiroku] version (available on nyaa)
i got the subtitle on [sub link](https://www.kitsunekko.net/subtitles/japanese/Neon%20Genesis%20Evangelion/The%20End%20of%20Evangelion.CC.ja.srt) with -1000 ms delay
The word that I add to Anki (via yomichan) are 約束. and after that, I press C in MPV and then press M.
the audio is created (images 2) but I cannot play it (tested using another music player but did not play just stuck at 00;00)

**Expected behavior**
I expect the audio would play just like any other scene.

the only possible reason why I think this might be happening is that I click the preview button too early before the audio load properly(?). but I already deleted the card and try again, but the audio still cannot be played. so I don't know why this happened.

**Comment by tatsumoto-ren** [comment]
Read [issue.md](https://github.com/Ajatt-Tools/mpvacious/blob/master/.github/ISSUE_TEMPLATE/issue.md)

So the word is 約束 and the timestamp is 4:45. I'll try, but I doubt it's reproducible. Also you may want to change the encoder from mpv to ffmpeg or back.

**Comment by ismi-ismi** [comment]
i fi

**Comment by ismi-ismi** [comment]
oh shit, sorry about the closed and reopen thing, I accidentally click it.

and about the audio problem, I manage to fix it by making the sub delay to -1200 ms. it is now working as normal
