### ISSUE TITLE
Web view

### ISSUE THREAD

**Issue by SumZbrod** [Ajatt-Tools/mpvacious#80]
- The add-on crashes? no
- The add-on stopped working? no
- Have a feature request? yes

1) Windows 10
3) mpv 0.34.0-429-g37aea112c1 
4) Couldn't store file 's4PyUJmlA4Qt332_05m29s067ms-05m30s300ms.mp3': [Errno 2] No such file or directory: 'C:\\Users\\PROFES~1\\AppData\\Local\\Temp/s4PyUJmlA4Qt332_05m29s067ms-05m30s300ms.mp3'

When watching a video without downloading, like so:
mpv https://www.youtube.com/watch?v=s4PyUJmlA4Q
When you try to create a card from such a video, the metadata is not transferred to the card.

**To Reproduce**
1) mpv https://www.youtube.com/watch?v=s4PyUJmlA4Q
2) a + s + 'wait' + n 

**Expected behavior**
Changing the video file search algorithm

**Comment by tatsumoto-ren** [comment]
Creating cards from streamed content will often fail. I think it's an issue with mpv and not mpvacious.

https://tatsumoto-ren.github.io/blog/mining-from-movies-and-tv-shows.html#download-content

But I'm open to suggestions, maybe someone knows a better workaround.

**Comment by tatsumoto-ren** [comment]
Another note: FFmpeg encoder can't create media files from remote content.

https://github.com/Ajatt-Tools/mpvacious/blob/master/.github/RELEASE/subs2srs.conf#L38
