### ISSUE TITLE
subs2srs.lua module/file not found

### ISSUE THREAD

**Issue by Madu777** [Ajatt-Tools/mpvacious#84]
subs2srs.lua does not work for me :( somebody help me please
![L1xUMnotwC](https://user-images.githubusercontent.com/118694778/202928930-fe1b8ec3-1b9c-4043-b844-3625bf1e661f.png)

**Comment by tatsumoto-ren** [comment]
See [issue.md](https://github.com/Ajatt-Tools/mpvacious/blob/master/.github/ISSUE_TEMPLATE/issue.md)

**Comment by tatsumoto-ren** [comment]
From the logs it looks like you installed the script in the wrong folder.
