### ISSUE TITLE
Can't make addon to work

### ISSUE THREAD

**Issue by Quezako** [Ajatt-Tools/mpvacious#89]
Hello,

Windows 11 22H2
mpv version: 0.35.0-dirty (included with SVP 4)

I've managed to make yomichampv working, but I can't make mpvacious working.
It seems that it's not detected. When I hit A or ctrl+T, nothings shows or happens.
The .lua files are in C:\Users\Quezako\AppData\Roaming\mpv\scripts\

I don't know how to "debug" and find if the addon is not loaded or is loaded but not working.

**Comment by tatsumoto-ren** [comment]
Put .lua files in `C:\Users\Quezako\AppData\Roaming\mpv\scripts\subs2srs`.

**Comment by Quezako** [comment]
Oh, I see, I must have been tired 😅
I read "Download the repository or the latest release and extract the folder containing subs2srs.lua to your mpv scripts directory."
But I didn't see "Expected directory tree"
Thank you very much for the help!

**Comment by tatsumoto-ren** [comment]
Glad I could help.
