### ISSUE TITLE
Media files not being created/imported to Anki

### ISSUE THREAD

**Issue by wowregistering** [Ajatt-Tools/mpvacious#9]
**Environment:**
 - OS: Windows
 - OS 10
 - mpv version
mpv 0.32.0-791-g73be20143e Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  1 10:19:46 +08 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.100
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.88.100
   libswresample   3.8.100
FFmpeg version: git-2020-10-31-3da35b7c

I am having trouble getting the media to properly create itself and import to Anki.
The subtitles properly get added to the field on the Anki Card but the videofilename_(starttime-endtime).ogg file and snapshot.webp Do not seem to be created.

I have tried searching for an ogg file with the name it attempts to put in the anki audio field but find nothing, the snapshot just shows up as a small icon with 'snapshot' in text after it.

There are no errors showing up in the MPV console

Attempting to make a card in any way

![Add_anki_2020-11-07_04-17-48](https://user-images.githubusercontent.com/32309624/98437457-34f90500-20b0-11eb-9190-f67904c1cf27.png)

The above screenshot is what the snapshot shows, instead of showing a frame of the media the card is being created from.

**Comment by KamiGim** [comment]
I change snapshot_format to jpg and it works

**Comment by tatsumoto-ren** [comment]
I can't believe this is happening to you. Do you get the notification about missing files when you run `Tools` -> `Check Media...` in Anki? I just tested the add-on in a virtual machine running Windows 10 and nothing seems to be broken.

**Comment by wowregistering** [comment]
Yes, after attempting to create a card and then running Tools -> Check Media...  I have 
"Used on cards but missing from media folder;" followed by the missing .webp, .ogg, .mp3, and .jpg files.

I attempted to swap the formats as KamiGim did for his snapshot_format but that did not result in any different behavior.

**Comment by wowregistering** [comment]
Follow up post, I am sorry that I did not realize this on my own before making this post.

In subs2srs.lua there is a line that reads
"collection_path = "",       -- full path to the collection. most users should leave it empty."
I mistakenly ignored this setting until now after reading "most users should leave it empty".

The post about 'tools -> check media' and 'changing snapshot_format' are what made me realize I probably should not have ignored that setting.

I am running Anki in portable mode, this causes my collection file to not be in the normal location and I failed to realize that I would need to manually set it.  I am going to assume that not many people actually use Anki set to portable/self contained and that is why there was no installation documentation on if you need to set the collection_path manually or not.


Steps to resolve my problem:
1: Open subs2srs.lua
2: Set collection_path to the path of my portable Anki Collection folder.

**Comment by tatsumoto-ren** [comment]
Yes, if your collection differs from the default, `collection_path` is the setting for you. It can be set from the config file as well. The setting is left there for debugging and I didn't realize someone actually may need it. Does your problem get solved after setting it? If so, I should leave a note in the README file about it.

**Comment by wowregistering** [comment]
Yes, this has completely resolved the issue for me, thank you for the replies and assistance.

It is working with no issues now using both a portable Anki and portable MPV install.

**Comment by tatsumoto-ren** [comment]
Glad to see that! I will add a note to the readme about this.
