### ISSUE TITLE
Failed to add card, loading external audio file to video

### ISSUE THREAD

**Issue by czqhurricnae** [Ajatt-Tools/mpvacious#93]
**Environment**

1)   macOS
2)  Catalina
3) mpv version: 0.35.0
4) log
```
[mpvacious_master] ...s/c/.config/mpv/scripts/mpvacious-master/encoder.lua:204: bad argument #2 to 'format' (number expected, got string)
```

**Describe the bug**
When mpv plays a video adding with a external audio file, failed to add card due to function `ffmpeg.make_audio_args` crashed.

https://github.com/Ajatt-Tools/mpvacious/blob/f2e06130c5d086a046c90c6c6ddba11feb17b6c3/encoder.lua#L147-L172

Because under this circumstance, `audio_track` and `audio_track.external` are both ture,

```
if audio_track and audio_track.external == true then
        source_path = audio_track['external-filename']
        audio_track_id = 'a'
    end
```
So `audio_track_id = 'a'`,  `audio_track_id` is a string now, but number is expected, and can not be formated correctly in ` '-map', string.format("0:%d", audio_track_id),`.

**To Reproduce**

```
mpv video.mp4 --audio-file=audio.m4a

```
set start time and end time then try to clip a new card, but MPV do nothing and throw the error message which I just report.

**Comment by tatsumoto-ren** [comment]
Make sense. Setting audio track id to 'a' is a form of saying "take the default track". To fix this you can make a PR that replaces %d with %s.
