### ISSUE TITLE
Add an option to create text-only cards

### ISSUE THREAD

**Issue by asakura42** [Ajatt-Tools/mpvacious#97]
For example, I have a source in a non-target language but with target subtitles. I want to create a map from it, but I don't want to add audio because it would be useless. What can I do in this case?

**Comment by tatsumoto-ren** [comment]
Open `subs2srs.conf` and add 

```
audio_field=
image_field=
```

**Comment by asakura42** [comment]
> Open `subs2srs.conf` and add
> 
> ```
> audio_field=
> image_field=
> ```

Do you think about adding some hotkey for it? I watch videos with target language usually, but editing subs2srs.conf every time I stumble upon videos with non-target lang or difference between voice and subs is too *manual* lol.

**Comment by tatsumoto-ren** [comment]
You can create a new profile with these settings and switch to it by pressing <kbd>p</kbd>.
