### ISSUE TITLE
unexpected sentence trimming

### ISSUE THREAD

**Issue by Geniusssmit** [Ajatt-Tools/mpvacious#99]
**Environment**

1) OS name  win 10
2) OS version 1809
3) mpv version latest build mpv-x86_64-v3-20230528-git-959ef84

**Describe the bug**
mpvacious trims characters inside brackets when updating card("mpvacious-overwrite-last-note", menu:with_update) even tho settings are set correctly

nuke_spaces=no
clipboard_trim_enabled=no

it doesn't trim clipboard as expected, but trims on the card when updating it

**To Reproduce**

nuke_spaces=no
clipboard_trim_enabled=no
update card

**Expected behavior**
in sentence field
```（アーニャ） あっ モジャモジャ```
but it's 
```あっ モジャモジャ```

**Comment by tatsumoto-ren** [comment]
Since `clipboard_trim_enabled` is a setting that only applies to the clipboard, the described behavior is expected. If you think about it logically, you don't want `（アーニャ）` on your flashcard because it's not a part of the sentence.

**Comment by Geniusssmit** [comment]
Actually I wanted it on my card. It was unexpected for me IG, anyway that's not a big deal.

**Comment by tatsumoto-ren** [comment]
If your use-case is different and you want the full subtitle line to appear on your card, I don't mind adding a new option in the config file. Feel free to submit a PR that does that.

**Comment by tatsumoto-ren** [comment]
There's no limit. It's an interesting bug though.

**Comment by nairyosangha** [comment]
interesting that it's exactly 500 characters, this might have something to do with it https://github.com/mpv-player/mpv/blob/bc4003d21901ae1bb012bd8aa51022360607f48a/sub/sd_ass.c#L54

I'm getting the same result btw
